### ISSUE TITLE
dll error inject

### ISSUE THREAD

**Issue by cutelake123321** [atizoff/mrc_remake#2]
thanks for your repository, at the moment of injecting it gives an error and does not inject, try with several injectors, also try the mapmanual mode

at the time of compiling it asks for precompiled information from the ph.h file it creates it, and the same thing happens
and when disabling this, the same thing also happens, I think there is some error in the memory writing address

**Comment by atizoff** [comment]
Hello! It`s all because you need to use CreateThread().

void initThread()
{
	Sleep(10000);
        vmtHook.bInitialize((PDWORD64*)SSystemGlobalEnvironment::Singleton()->GetISystem());
        oUpdate = (m_pUpdate)vmtHook.dwHookMethod((DWORD64)hkUpdate, 4);
}


BOOL WINAPI DllMain(HMODULE hModule, DWORD64 dwReason, LPVOID)
{
          if (dwReason == 1) 
          {
                    CloseHandle(CreateThread(NULL, NULL, reinterpret_cast<LPTHREAD_START_ROUTINE>(initThread), NULL, NULL, NULL));
          }
          return true;
}
